### ISSUE TITLE
need safety controller to prevent motion when arm extended

### ISSUE THREAD

**Issue by jack-oquin** [utexas-bwi/segbot_arm#5]
The necessary infrastructure for pausing robot motion is already integrated into the system:
- [stop_base package](https://github.com/utexas-bwi/bwi_common/blob/master/stop_base/README.rst)
- [StopBase service](http://docs.ros.org/indigo/api/bwi_msgs/html/srv/StopBase.html)
- [StopBaseStatus message](http://docs.ros.org/indigo/api/bwi_msgs/html/msg/StopBaseStatus.html)

The desired safety controller should continually monitor arm position, requesting the base to PAUSE whenever the arm is not in a safe position within the robot's radius.

**Comment by maxsvetlik** [comment]
Commit e7652 brought my old [mico safety service](https://github.com/utexas-bwi/segbot_arm/blob/master/moveit_utils/src/mico_nav_safety_service.cpp) up to speed.

Currently, this service: 
- uses Moveit!'s inverse kinematic abilities to obtain position information for each joint
- publishes to /mico_nav_safe whether or not all joints are within the robot radius
- at request, will move to a default safe position

Since it uses Moveit!, the mico_moveit.launch in moveit_utils will need to be up before running the service. I still need to clean a few things up, but overall it is functional and can be used by a controller

**Comment by jack-oquin** [comment]
That code does not actually stop the robot base yet. Right? It just looks to see if the arm is in a safe pose. I think I could easily write a stop base client using that.

But, that would still leave the arm at risk if someone is controlling it without using MoveIt. Right?

Is the default rest pose considered safe for navigation?

**Comment by maxsvetlik** [comment]
My impression is that Moveit!'s IK service is independent of control method; I think it relies on joint_states which could be changed by a Jaco action, someone playing with the tethered controller, etc. That said, it'd be worth testing

Yes, the default pose is safe for navigation

**Comment by jack-oquin** [comment]
That sounds promising. By all means, let's test it.

**Comment by maxsvetlik** [comment]
I've tested this and it works as I assumed; regardless of control method.

I also quickly wrote in a service call to stop_base. After a bit of testing, I can see that stop_base is receiving the 'pause' request, but movement isn't preempted (twist commands and goal poses were carried out despite stop_base's status). I'm assuming this isn't normal behavior? Or has it not been fully integrated?

**Comment by jack-oquin** [comment]
It should work. Let's test it tomorrow.

**Comment by maxsvetlik** [comment]
Tested and works. Closed by 5936fb5
